---
- name: configure api server
  ini_file:
      dest: '{{ kube_apiserver_conf }}'
      section: ""
      option: '{{ item.option }}'
      value: '{{ item.value }}'
  with_items:
      - option: KUBE_API_ADDRESS
        value: '"--address=0.0.0.0"'
      - option: KUBE_API_PORT
        value: '"--port=8080"'
      - option: KUBE_SERVICE_ADDRESSES
        value: '"--service-cluster-ip-range={{overlay_net}}"'

- name: start etcd
  service:
      name: etcd
      state: started
      enabled: yes

- name: store config on master
  command: etcdctl mkdir /kube-centos/network
  ignore_errors: yes

- name: put network to etcd
  command: 'etcdctl mk /kube-centos/network/config "{ \"Network\": \"{{overlay_net}}\", \"SubnetLen\": 24, \"Backend\": { \"Type\": \"vxlan\" } }"'
  ignore_errors: yes

- name: start services
  service:
      name: '{{ item }}'
      state: started
      enabled: yes
  with_items:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler
      - flanneld
      - etcd
