---
- name: restart etcd
  service:
    name: etcd
    state: restarted

- name: restart kube apiserver
  service:
      name: kube-apiserver
      state: restarted

- name: restart flanneld
  service:
      name: flanneld
      state: restarted

- name: restart kubelet
  service:
      name: kubelet
      state: restarted
